<?php
$users = array(
  array("Name"=>"Daniel Lewis", "User-id" => 1, "Avatar"=>'<img src="avatars/Daniel.jpg" width="100px" height="100px">', "Username"=>"Danne", "Password"=>"Danne123"),
  array("Name"=>"Tom Cruise", "User-id" => 2, "Avatar"=>'<img src="avatars/Cruise.jpg" width="100px" height="100px">', "Username"=>"Tom", "Password"=>"Tom123"),
  array("Name"=>"Mark Wahlberg", "User-id" => 3, "Avatar"=>'<img src="avatars/Mark.jpg" width="100px" height="100px">', "Username"=>"Mark", "Password"=>"Mark123"),
  array("Name"=>"Samwise Gamgee", "User-id" => 4, "Avatar"=>'<img src="avatars/Samwise.jpg" width="100px" height="100px">', "Username"=>"Samwise", "Password"=>"Samwise123"),
  array("Name"=>"Elijah Wood", "User-id" => 5, "Avatar"=>'<img src="avatars/Elijah.jpg" width="100px" height="100px">', "Username"=>"Elijah", "Password"=>"Elijah123"),
);

$posts = array(
  array("Title"=>"En titel", "Text"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin commodo neque vitae nunc pretium, fermentum blandit turpis blandit. Praesent convallis justo eget libero porttitor fermentum. Nam in ipsum elementum, tincidunt nisl nec, rutrum nunc. Sed varius est ac dolor facilisis, at aliquet velit iaculis. Sed mollis nulla et volutpat malesuada. Aenean bibendum urna lorem, quis tempus velit consequat nec. Praesent efficitur egestas euismod. Nunc auctor sapien sapien, id pellentesque elit ullamcorper et.",
   "Author"=>$users[0]["Name"], "Date"=>"2016-07-23", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Integer in massa tincidunt, hendrerit nunc et, faucibus mauris. Suspendisse tincidunt, dolor a mattis convallis, ex eros fermentum turpis, in aliquam purus turpis a leo. Morbi sit amet libero sed odio bibendum ullamcorper a ut mauris. Integer scelerisque quam lorem, in congue velit ullamcorper ut. Suspendisse urna leo, porta et massa id, ullamcorper euismod erat. Fusce ullamcorper ligula justo, ac finibus lacus volutpat eu. Integer commodo hendrerit dui, at interdum arcu bibendum eget. Sed gravida urna non pharetra tristique. Cras quis vestibulum lorem.",
   "Author"=>$users[0]["Name"], "Date"=>"2016-02-27", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Phasellus convallis enim a nunc placerat imperdiet. Quisque scelerisque velit a facilisis hendrerit. Curabitur tincidunt euismod dui, vel posuere diam condimentum quis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque iaculis, lectus vitae eleifend sodales, massa magna finibus mi, pulvinar pharetra eros elit vel ex. Sed dapibus aliquet nunc, at varius elit convallis et. Vivamus egestas elit feugiat urna sollicitudin, in hendrerit libero cursus. Mauris vel risus hendrerit, consectetur purus non, mollis dui.",
   "Author"=>$users[0]["Name"], "Date"=>"2016-09-09", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Praesent ac vestibulum odio, id aliquet erat. Duis scelerisque luctus facilisis. Praesent rutrum volutpat vehicula. Ut eget tortor eget augue pharetra semper at sit amet tortor. Integer blandit ut dolor eu aliquet. Aliquam erat volutpat. In gravida, magna id tincidunt rutrum, lorem nulla tempus risus, vitae ullamcorper est nulla ornare sem. Aenean suscipit auctor fringilla. Morbi consequat gravida tristique. In semper nunc mauris, a venenatis eros molestie sed. Vestibulum mollis hendrerit turpis non euismod. Aenean mauris nulla, gravida non venenatis sed, ornare sit amet lectus.",
   "Author"=>$users[0]["Name"], "Date"=>"2016-04-15", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Cras suscipit hendrerit neque non imperdiet. Proin vestibulum nisl volutpat, imperdiet purus et, bibendum magna. Nunc viverra ipsum eget tortor venenatis aliquet. Sed tincidunt urna neque, a placerat augue tempor at. Morbi eget orci a erat luctus consequat. Etiam ut lorem eu mi congue gravida. Cras nunc elit, efficitur nec hendrerit in, ullamcorper sit amet augue. Nulla congue libero nulla, laoreet porta mauris tincidunt sed. Etiam tellus nisl, semper a turpis eu, varius sollicitudin nunc. Pellentesque mollis viverra quam, vitae ultricies leo tincidunt eu. Sed in felis massa. Nunc non egestas purus. Aenean faucibus, lacus aliquet pharetra convallis, magna urna scelerisque urna, ullamcorper tempor leo enim ac nunc.",
   "Author"=>$users[0]["Name"], "Date"=>"2016-03-23", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Proin in vulputate dui. Nam id mi ipsum. Proin accumsan mauris ac purus hendrerit rhoncus. Nunc interdum lacus vitae auctor viverra. Nulla at tortor lacus. Maecenas auctor ultrices egestas. Suspendisse scelerisque augue ut viverra elementum. Aliquam varius magna a cursus mollis. Proin accumsan urna placerat, volutpat purus sollicitudin, luctus magna. Etiam hendrerit bibendum venenatis. Ut vehicula maximus magna, et aliquet diam consequat vel. Cras ullamcorper, nisi quis pellentesque lobortis, diam dui hendrerit purus, vel tristique elit velit quis nisi.",
   "Author"=>$users[1]["Name"], "Date"=>"2016-05-09", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Nullam eu cursus tellus, nec ullamcorper ligula. Vestibulum id nunc a nisl aliquet ultricies a non ligula. Phasellus rutrum tempor purus, et posuere mi vehicula quis. Etiam maximus tempor arcu quis ullamcorper. Maecenas convallis congue tellus. Integer tristique, leo sit amet dignissim pharetra, sem metus congue mauris, et feugiat ligula turpis sed nisl. Fusce sodales diam non urna ultrices faucibus volutpat sit amet libero. Integer hendrerit, quam a gravida laoreet, velit felis tempor nisi, ac lobortis orci lacus id orci. Sed blandit arcu neque, vel fermentum massa rutrum et. Proin quis ultricies orci, quis vulputate sapien. Ut arcu augue, elementum et massa sit amet, blandit malesuada metus. Aliquam malesuada luctus diam sed accumsan. Sed tempus semper diam in accumsan.",
   "Author"=>$users[1]["Name"], "Date"=>"2016-07-19", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Mauris sollicitudin diam id rhoncus fringilla. Morbi libero diam, vestibulum id justo a, fermentum sagittis diam. Vivamus malesuada sodales massa at sodales. Fusce volutpat massa eu neque luctus, nec pellentesque ex condimentum. Praesent posuere pharetra risus sed egestas. Praesent dapibus sollicitudin eros. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam iaculis tincidunt est. Duis lectus nibh, lobortis sed commodo vel, dignissim et nibh.",
   "Author"=>$users[1]["Name"], "Date"=>"2016-09-25", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Ut hendrerit ipsum a pharetra pulvinar. Morbi ac eros auctor risus imperdiet posuere. Aenean lobortis, dui et convallis hendrerit, erat ligula cursus eros, nec sodales elit eros in velit. Sed in nisi a odio maximus condimentum in sit amet massa. Etiam molestie ante ac enim laoreet blandit. Mauris enim neque, auctor a tortor et, efficitur consequat tellus. Sed interdum interdum dui, ac hendrerit est rhoncus eget. Sed a molestie nibh, eu interdum mi. Aliquam nec bibendum velit. Nam a tristique dolor.",
   "Author"=>$users[1]["Name"], "Date"=>"2016-06-04", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Nam congue iaculis mi, quis molestie dui aliquam quis. Donec vel tortor neque. Aliquam suscipit tempus tempus. Nunc sit amet sollicitudin lectus. Phasellus eu congue quam. Sed faucibus leo dolor, non dapibus elit pellentesque vitae. Sed a interdum enim. Vestibulum ultrices turpis quis lobortis lobortis. Pellentesque quam leo, convallis at mattis et, facilisis vel enim. Nullam lacinia nisl nec convallis fermentum. Aliquam a aliquam leo.",
   "Author"=>$users[1]["Name"], "Date"=>"2016-09-11", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Nam suscipit augue ac elit euismod, et pulvinar elit bibendum. Morbi quis arcu sed dolor luctus rutrum sit amet id nulla. Cras quis neque sit amet lorem eleifend hendrerit in sed mi. Sed sed tellus massa. Etiam lectus odio, ullamcorper a dictum eget, pretium eget sapien. Mauris sodales condimentum ex. Phasellus accumsan feugiat enim quis bibendum. Donec eget dapibus lorem, nec tincidunt leo. Aenean in nibh consectetur orci porttitor consequat quis quis ante. Aenean ac magna at nisl feugiat aliquet ut at sapien. Morbi a interdum dolor. Fusce pharetra semper placerat. Aliquam consectetur arcu sit amet aliquam feugiat.",
   "Author"=>$users[2]["Name"], "Date"=>"2016-04-14", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Suspendisse potenti. In pharetra feugiat faucibus. Proin porta purus quis risus maximus, eu venenatis ligula finibus. Duis tincidunt nisl ut vehicula varius. Maecenas consequat lectus neque, sit amet laoreet neque accumsan vitae. Etiam aliquam sodales malesuada. Donec laoreet non lorem id vestibulum. Suspendisse luctus arcu sit amet leo sodales, ac tempus nisl iaculis. Donec vulputate mollis faucibus. Integer justo lacus, laoreet et eleifend et, scelerisque sed quam. Praesent metus eros, euismod vitae libero sollicitudin, sollicitudin aliquet purus. Proin mollis facilisis ex non iaculis. Vivamus nec scelerisque lorem.",
   "Author"=>$users[2]["Name"], "Date"=>"2016-06-22", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Vivamus ornare ultrices elit, et porta leo porta faucibus. Ut at sapien ex. Pellentesque sed varius nulla. Phasellus id laoreet enim. Quisque lectus lorem, sagittis id orci sit amet, egestas ultrices tortor. Morbi a posuere augue. Quisque vitae diam fermentum, condimentum neque eget, volutpat purus.",
   "Author"=>$users[2]["Name"], "Date"=>"2016-02-11", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Curabitur sed sapien in risus luctus ultrices sed vel metus. Ut consectetur aliquet elit quis egestas. Quisque sed ante finibus, commodo eros non, laoreet odio. Integer aliquam dignissim urna vitae volutpat. Integer non pretium justo. Cras venenatis justo in porttitor accumsan. Phasellus nisi erat, gravida ac lacinia quis, elementum a quam. Donec vulputate vitae elit ut laoreet. Aenean a sodales lacus.",
   "Author"=>$users[2]["Name"], "Date"=>"2016-02-17", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Morbi auctor libero ante, nec imperdiet eros commodo fringilla. Nam eu sapien in massa malesuada convallis. Aliquam aliquet ornare lobortis. Mauris ac blandit lacus. Vestibulum tincidunt enim ac ipsum placerat mollis. Sed elementum felis a pellentesque luctus. Proin luctus lobortis ex nec interdum. In nibh felis, mollis eu ligula ut, egestas aliquet dui. Ut ultricies nisl quis ante fringilla pharetra. Sed non commodo felis. Phasellus maximus risus accumsan luctus commodo.",
   "Author"=>$users[2]["Name"], "Date"=>"2016-07-18", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Donec ut hendrerit diam. Nulla sagittis porttitor nisi id volutpat. Cras sit amet ultricies ex, in mattis odio. Fusce finibus dolor eget ultrices tempor. Nullam eu odio egestas, tristique nunc id, mattis nunc. Ut pellentesque, libero in fringilla volutpat, erat ligula porta ex, a faucibus lacus enim vitae purus. Nunc ac luctus arcu. Aenean quis risus justo. Nam dignissim rutrum leo. Morbi volutpat augue sed eleifend varius.",
   "Author"=>$users[3]["Name"], "Date"=>"2016-04-01", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Integer a orci semper, malesuada felis nec, vestibulum diam. Suspendisse potenti. Sed id ultrices leo. Quisque cursus elit at vestibulum dictum. Sed gravida leo id semper commodo. Ut egestas, libero vel pellentesque hendrerit, leo orci aliquet enim, vitae ullamcorper urna est ac ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla molestie nisl mi, porttitor placerat ipsum convallis et. Aenean posuere in mauris interdum maximus. Donec eget libero sit amet neque cursus placerat. Aliquam erat volutpat. Donec placerat, velit eu blandit luctus, urna ex rhoncus eros, at facilisis nunc lorem id mi. Fusce euismod volutpat vehicula.",
   "Author"=>$users[3]["Name"], "Date"=>"2016-04-21", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Curabitur gravida id eros eget ultrices. Proin vitae vestibulum quam, at tempor leo. Donec vitae tellus eu quam pulvinar laoreet. Donec dapibus arcu in dolor lacinia, in lacinia magna ultrices. Nunc ac neque id risus consectetur malesuada. Donec interdum elit sit amet consectetur maximus. Sed sed lorem vitae diam rutrum dictum ut at lectus.",
   "Author"=>$users[3]["Name"], "Date"=>"2016-09-26", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Sed sit amet urna libero. Praesent vel magna volutpat, sodales augue ut, mollis ante. Nunc eros est, pellentesque nec eros sed, laoreet fermentum velit. Nulla iaculis leo in viverra egestas. Quisque nisl dui, consectetur non sem eget, congue fermentum magna. Nam vehicula euismod ultrices. Phasellus vulputate laoreet posuere. Praesent at diam volutpat, mollis mauris ultrices, interdum mi. Maecenas at ante in mauris ultrices consectetur et et elit. Aliquam vehicula lacus quis dui viverra dapibus.",
   "Author"=>$users[3]["Name"], "Date"=>"2016-01-30", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Nunc maximus ipsum ac arcu semper sollicitudin. Aliquam ultricies libero et fermentum sodales. Pellentesque in iaculis dui. Etiam efficitur neque lacus, ac ultricies leo gravida vel. Cras quis magna commodo, euismod enim posuere, pretium nisl. Etiam nec tempus dolor, id porta ligula. Nulla pharetra faucibus nisi, bibendum tincidunt eros placerat vitae. Cras ornare mauris mauris, at ornare massa dapibus sed. Vestibulum maximus lacus turpis, eu rutrum libero sagittis tristique.",
   "Author"=>$users[3]["Name"], "Date"=>"2016-01-04", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Cras eget magna enim. Vivamus et euismod neque. Phasellus sit amet nibh orci. Morbi suscipit elit sed ullamcorper pellentesque. Nulla odio risus, scelerisque at lacinia ac, imperdiet a est. Sed eget facilisis nunc, ac vehicula sem. Maecenas vitae tincidunt justo. Mauris maximus accumsan sapien, in convallis velit feugiat ut. Quisque pharetra pretium tincidunt.",
   "Author"=>$users[4]["Name"], "Date"=>"2016-02-07", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Cras nec feugiat neque. Quisque maximus velit eget felis mollis maximus. Integer a sapien nisi. Integer eget interdum metus. Ut eget orci nisi. Ut purus velit, dignissim eu molestie vel, eleifend dictum velit. Phasellus dolor ipsum, molestie et quam eu, ultricies euismod leo.",
   "Author"=>$users[4]["Name"], "Date"=>"2016-05-12", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Vivamus maximus dolor nec velit viverra euismod. Aenean non neque mollis, vehicula purus ullamcorper, pellentesque tellus. Donec id cursus mi. Nulla efficitur egestas ex. Cras vehicula ex gravida purus lobortis pulvinar. Donec pharetra mi lorem, vitae sodales nunc viverra nec. Praesent lobortis malesuada libero, vitae tincidunt mauris. Nunc risus velit, tristique eget venenatis eu, lobortis et tortor. Curabitur libero dolor, varius vitae neque ac, mollis convallis neque. Ut vitae eleifend est, et sagittis mi. Etiam pulvinar consectetur nunc mattis finibus.",
   "Author"=>$users[4]["Name"], "Date"=>"2016-07-15", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Integer placerat non ante eget facilisis. Nam nec sodales felis. Pellentesque imperdiet fermentum placerat. Quisque varius sed diam ac tempor. Cras tristique ornare quam. Etiam libero arcu, placerat ut quam a, interdum dictum sem. Cras vel tortor vitae nunc imperdiet dapibus. Nunc ultricies commodo pulvinar. Cras at mi sed magna posuere ornare sed in eros.",
   "Author"=>$users[4]["Name"], "Date"=>"2016-02-19", "Likecounter"=>"Likes"),
  array("Title"=>"En titel", "Text"=>"Phasellus nec augue porttitor sapien feugiat aliquam consequat quis sem. In sapien lorem, mattis vel aliquam sed, ultricies non augue. Ut sed diam pretium, laoreet dolor sed, luctus urna. Ut neque mauris, euismod eget risus a, laoreet hendrerit neque. Mauris at lacinia mi. Cras vel nisi ultricies, vehicula lectus vitae, volutpat leo. Etiam volutpat porttitor congue. Sed ipsum dolor, maximus vitae eleifend dignissim, laoreet facilisis lorem. Fusce ornare libero nec massa lacinia, at scelerisque ipsum egestas. Aliquam rhoncus vulputate vulputate.",
   "Author"=>$users[4]["Name"], "Date"=>"2016-09-22", "Likecounter"=>"Likes"),
);

foreach ($posts as $key => $row) {
    $mid[$key]  = $row["Date"];
}
array_multisort($mid, SORT_DESC, $posts);


?>
